const styles = {
    body: {
      margin: 0,
      padding: 0,
      backgroundColor: '#ffffff',
    },
    navbar: {
      backgroundColor: '#f3f3f3',
      color: '#000000',
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: '5px',
      position: 'fixed',
      top: 0,
      width: '100%',
      zIndex: 999,
    },
    logo1: {
      width: '150px',
      height: 'auto',
    },
    menu: {
      listStyle: 'none',
      display: 'flex',
      margin: '0 10px',
      position: 'relative',
      transition: 'all 0.3s',
      fontSize: '20px',
    },
    menuLi: {
      margin: '0 10px',
    },
    menuLink: {
      textDecoration: 'none',
      color: '#000000',
    },
    inse: {
      color: '#000',
      borderRadius: '20px',
      backgroundColor: 'rgb(250, 60, 60)',
      color: 'white',
      padding: '10px 20px',
      border: 'none',
      cursor: 'pointer',
    },
    regis: {
      color: '#000',
      borderRadius: '20px',
      backgroundColor: 'rgb(61, 218, 82)',
      color: 'white',
      padding: '10px 20px',
      border: 'none',
      cursor: 'pointer',
    },
    button: {
      color: '#000',
      marginTop: '200px',
      marginRight: '200px',
      borderRadius: '20px',
      backgroundColor: 'rgb(61, 218, 82)',
      color: 'white',
      padding: '10px 20px',
      border: 'none',
      cursor: 'pointer',
    },
    inicio: {
      backgroundColor: '#ececec',
      listStyle: 'none',
      color: '#000000',
      padding: '10px',
      borderRadius: '20px',
      width: '900px',
      marginTop: '8%',
      position: 'relative',
      left: '6%',
      border: '0px solid #ececec',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    imginicio: {
      marginLeft: '0px',
      width: '450px',
      height: 'auto',
      borderRadius: '50px',
      boxShadow: '4px 4px 10px rgba(0, 0, 0, 08)',
    },
    inicioH1: {
      marginRight: '-290px',
      marginTop: '-10px',
    },
    inicio2: {
      textAlign: 'center',
      color: 'black',
      marginLeft: '80px',
      marginRight: '60px',
    },
    inicio2H4: {
      color: '#504e4e',
    },
    icons: {
      textAlign: 'center',
      marginTop: '50px',
      display: 'flex',
      paddingLeft: '180px',
    },
    icons1: {
      textAlign: 'center',
      width: '90px',
      height: '90px',
      backgroundColor: '#e5e5e5',
      textAlign: 'center',
      padding: '10px',
      marginRight: '150px',
      borderRadius: '20px',
    },
    icons1Img: {
      textAlign: 'center',
      maxWidth: '90%',
      maxHeight: '90%',
    },
    text1: {
      textAlign: 'center',
      marginRight: '-20px',
      marginLeft: '-20px',
      color: 'rgb(61, 218, 82)',
    },
    text2: {
      textAlign: 'center',
      marginRight: '-20px',
      marginLeft: '-20px',
      color: 'rgb(61, 218, 82)',
    },
    text3: {
      textAlign: 'center',
      marginRight: '-20px',
      marginLeft: '-20px',
      color: 'rgb(61, 218, 82)',
    },
    icons1H4: {
      textAlign: 'center',
      marginRight: '-50px',
      marginTop: '-10px',
      marginLeft: '-50px',
    },
    table: {
      marginTop: '14%',
      marginLeft: '30%',
    },
    tableH2: {
      marginLeft: '55px',
    },
    miTabla: {
      textAlign: 'center',
      width: '50%',
      borderCollapse: 'collapse',
      margin: '20px',
    },
    miTablaTh: {
      backgroundColor: 'rgb(61, 218, 82)',
      color: '#fff',
      textAlign: 'center',
      padding: '10px',
    },
    miTablaEven: {
      backgroundColor: '#f2f2f2',
    },
    miTablaTd: {
      padding: '10px',
      border: '1px solid #ccc',
    },
    chequeImg: {
      maxWidth: '15%',
      maxHeight: '15%',
    },
    preview: {
      textAlign: 'center',
    },
    preview1: {
      textAlign: 'center',
      display: 'flex',
      marginLeft: '10%',
      transition: 'transform 1s',
      position: 'relative',
    },
    preview2: {
      textAlign: 'center',
      display: 'flex',
      marginLeft: '10%',
      transition: 'transform 1s',
      position: 'relative',
    },
    previewImg: {
      textAlign: 'center',
      width: '40%',
      height: '40%',
      padding: '34px',
      borderRadius: '20px',
      transition: 'transform 0.3s',
    },
    previewImg2: {
      textAlign: 'center',
      width: '40%',
      height: '40%',
      padding: '34px',
      borderRadius: '20px',
      transition: 'transform 0.3s',
    },
    previewImgHover: {
      transform: 'scale(1.2)',
    },
    agenda: {
      marginTop: '11%',
    },
    footer: {
      backgroundColor: '#333',
      color: '#fff',
      padding: '2px',
      display: 'flex',
    },
    contacto: {
      width: '50%',
      float: 'left',
      boxSizing: 'border-box',
      padding: '20px',
    },
    contactoH2: {
      fontSize: '24px',
      marginTop: '10px',
    },
    contactoP: {
      fontSize: '16px',
      margin: '10px',
      color: '#fff',
      textDecoration: 'none',
    },
    contactoPBefore: {
      content: '""',
      marginRight: '5px',
    },
    container: {
      width: '95%',
      maxWidth: '900px',
      padding: '32px 64px',
      margin: 'auto',
    },
    social: {
      width: '35px',
      position: 'fixed',
      top: '50px',
      right: 0,
    },
  };
  
  export default styles;
  